package com.platform.domain.model;

public enum AuditEventType {
    INGESTION,
    STATE_TRANSITION,
    FIELD_UPDATE,
    ASSIGNMENT,
    ROUTING_FALLBACK,
    MAKER_CHECKER_APPROVAL,
    GROUP_REASSIGNMENT,
    CHILD_WORKFLOW_CREATED,
    ATTACHED_TO_EXISTING_CHILD,
    DEPENDENCY_RESOLVED,
    SLA_WARNING,
    SLA_BREACH,
    DUPLICATE_INGESTION_DISCARDED,
    TRANSITION_FAILED
}
