plugins {
    java
    id("org.sonarqube") version "7.4.0.8496"
    id("org.openrewrite.rewrite") version "7.39.0"
}

rewrite {
    activeRecipe("org.openrewrite.java.spring.boot4.UpgradeSpringBoot_4_0")
}

dependencies {
    rewrite(libs.rewrite.spring)

    runtimeOnly("javax.xml.bind:jaxb-api:2.3.1")
}

allprojects {
    group = "com.platform"
    version = "0.0.1-SNAPSHOT"

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply(plugin = "java")
    apply(plugin = "jacoco")

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    tasks.withType<Test> {
        useJUnitPlatform()
        testLogging {
            events("passed", "skipped", "failed")
        }
        finalizedBy(tasks.named("jacocoTestReport"))
    }

    tasks.named<JacocoReport>("jacocoTestReport") {
        dependsOn(tasks.withType<Test>())
        reports {
            xml.required = true
            html.required = true
        }
        // Exclude generated classes, Spring Boot config, and Cucumber runners from coverage
        classDirectories.setFrom(
            files(classDirectories.files.map {
                fileTree(it) {
                    exclude(
                        "**/*Application*",
                        "**/config/**",
                        "**/CucumberSuiteTest*"
                    )
                }
            })
        )
    }
}

sonar {
    properties {
        property("sonar.projectKey",  "user-workflow-platform")
        property("sonar.projectName", "User Workflow Platform")
        property("sonar.host.url",    "http://localhost:9000")

        // Java source sets are auto-discovered per subproject by the plugin.
        // Explicitly add the TypeScript frontend sources on top.
        property("sonar.sources",     "platform-frontend/src")
        property("sonar.tests",       "platform-frontend/step-definitions,platform-frontend/features")

        property("sonar.exclusions",  "**/build/**,**/node_modules/**,**/.gradle/**," +
                                      "**/dist/**,**/package-lock.json")

        // JaCoCo XML reports — one per subproject
        val jacocoReports = subprojects.map {
            "${it.projectDir}/build/reports/jacoco/test/jacocoTestReport.xml"
        }.joinToString(",")
        property("sonar.coverage.jacoco.xmlReportPaths", jacocoReports)

        // Frontend LCOV report (generated by c8)
        property("sonar.javascript.lcov.reportPaths", "platform-frontend/coverage/lcov.info")
    }
}

// Custom task: validate all JSON schemas (stub — implement in platform-config-engine)
tasks.register("validateConfigs") {
    group = "verification"
    description = "Validates all JSON configs in /schemas against their JSON Schema definitions and enforces cross-schema constraints."
    doLast {
        println("validateConfigs: not yet implemented — add implementation to platform-config-engine")
    }
}

// Generates TypeScript types from JSON schemas into platform-frontend/src/types/generated/
tasks.register<Exec>("generateTypes") {
    group = "build"
    description = "Generates Zod validators and TypeScript types from JSON schemas."
    commandLine("node", "scripts/generate-types.mjs")
}

// Runs the frontend BDD tests with c8 coverage (writes coverage/lcov.info)
tasks.register<Exec>("frontendTest") {
    group = "verification"
    description = "Runs the platform-frontend Cucumber BDD tests with coverage."
    workingDir("platform-frontend")
    commandLine("npm", "run", "test:coverage")
}

// Builds the frontend for production
tasks.register<Exec>("frontendBuild") {
    group = "build"
    description = "Builds the platform-frontend Vite application."
    workingDir("platform-frontend")
    commandLine("npm", "run", "build")
}

// Custom task: simulate priority scoring impact before deploying priorityConfig changes
tasks.register("simulatePriority") {
    group = "verification"
    description = "Simulates priority score impact of workflow-config.priorityConfig changes against live data."
    doLast {
        println("simulatePriority: not yet implemented — add implementation to platform-workflow")
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.add("-parameters")
}
