plugins {
    java
    id("org.sonarqube") version "7.4.0.8496"
    id("org.openrewrite.rewrite") version "7.39.0"
    id("org.owasp.dependencycheck") version "13.0.0"
}

rewrite {
    activeRecipe("org.openrewrite.java.spring.boot4.UpgradeSpringBoot_4_0")
}

dependencies {
    rewrite(libs.rewrite.spring)

    runtimeOnly("javax.xml.bind:jaxb-api:2.3.1")
}

allprojects {
    group = "com.platform"
    version = "0.0.1-SNAPSHOT"

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply(plugin = "java")
    apply(plugin = "jacoco")

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }

    tasks.withType<Test> {
        useJUnitPlatform()
        testLogging {
            events("passed", "skipped", "failed")
        }
        finalizedBy(tasks.named("jacocoTestReport"))
    }

    tasks.named<JacocoReport>("jacocoTestReport") {
        dependsOn(tasks.withType<Test>())
        reports {
            xml.required = true
            html.required = true
        }
        // Exclude generated classes, Spring Boot config/auto-config, and Cucumber runners from coverage
        classDirectories.setFrom(
            files(classDirectories.files.map {
                fileTree(it) {
                    exclude(
                        "**/*Application*",
                        "**/*AutoConfiguration*",
                        "**/config/**",
                        "**/CucumberSuiteTest*"
                    )
                }
            })
        )
    }

    tasks.named<JacocoCoverageVerification>("jacocoTestCoverageVerification") {
        dependsOn(tasks.named("jacocoTestReport"))
        violationRules {
            rule {
                excludes = listOf(
                    "*..*Application",
                    "*..*AutoConfiguration",
                    "*..config.*",
                    "*..CucumberSuiteTest"
                )
                limit {
                    counter = "LINE"
                    value = "COVEREDRATIO"
                    minimum = "0.80".toBigDecimal()
                }
            }
        }
        classDirectories.setFrom(
            files(classDirectories.files.map {
                fileTree(it) {
                    exclude(
                        "**/*Application*",
                        "**/*AutoConfiguration*",
                        "**/config/**",
                        "**/CucumberSuiteTest*"
                    )
                }
            })
        )
    }

    tasks.named("check") {
        dependsOn(tasks.named("jacocoTestCoverageVerification"))
    }

    // Declaring sonar.sources/sonar.tests once, flattened, at the ROOT sonar{} block causes the
    // Gradle plugin (7.4.0.8496, on Gradle 9.7.1) to register each subproject's files under a
    // scope that collides with its own auto-detected per-module registration — surfacing either
    // as "File not found in project sources" (JaCoCo coverage import can't resolve the file) or
    // "File ... can't be indexed twice" (main vs test set overlap), depending on what's set where.
    // The documented fix is to scope these per subproject, with paths relative to that subproject.
    sonar {
        properties {
            property("sonar.sources", "src/main/java")
            val testDirs = listOf("src/test/java", "src/testFixtures/java")
                .filter { file(it).exists() }
            property("sonar.tests", testDirs.joinToString(","))

            // Coverage import must be scoped per subproject too — a single root-level joined
            // list of all subprojects' report paths fails to resolve against each module's own
            // relatively-scoped sonar.sources above ("File not found in project sources").
            property("sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml")
        }
    }
}

sonar {
    properties {
        property("sonar.projectKey",  "user-workflow-platform")
        property("sonar.projectName", "User Workflow Platform")
        property("sonar.host.url",    "http://localhost:9000")

        // The root project itself has no Java sources — this scopes only to the frontend, which
        // isn't a Gradle subproject and so isn't covered by the per-subproject block above.
        property("sonar.sources", "platform-frontend/src")
        property("sonar.tests",   "platform-frontend/step-definitions,platform-frontend/features")

        property("sonar.exclusions",  "**/build/**,**/node_modules/**,**/.gradle/**," +
                                      "**/dist/**,**/package-lock.json,.claude/worktrees/**")

        // Frontend LCOV report (generated by c8)
        property("sonar.javascript.lcov.reportPaths", "platform-frontend/coverage/lcov.info")
    }
}

// OWASP Dependency-Check: scans JVM dependencies (all subprojects) against the NVD CVE database.
// Applied only at root — use `./gradlew dependencyCheckAggregate` to scan the whole multi-module build.
// CVSS 7.0+ (HIGH/CRITICAL) fails the build, matching the Sonar HIGH/CRITICAL gate in CLAUDE.md.
dependencyCheck {
    failBuildOnCVSS = 7.0f
    formats = listOf("HTML", "JSON")
    suppressionFile = "config/dependency-check-suppressions.xml"
    nvd.apiKey = System.getenv("NVD_API_KEY")
}

// Custom task: validate all JSON schemas (stub — implement in platform-config-engine)
tasks.register("validateConfigs") {
    group = "verification"
    description = "Validates all JSON configs in /schemas against their JSON Schema definitions and enforces cross-schema constraints."
    doLast {
        println("validateConfigs: not yet implemented — add implementation to platform-config-engine")
    }
}

// Generates TypeScript types from JSON schemas into platform-frontend/src/types/generated/
tasks.register<Exec>("generateTypes") {
    group = "build"
    description = "Generates Zod validators and TypeScript types from JSON schemas."
    commandLine("node", "scripts/generate-types.mjs")
}

// Runs the frontend BDD tests with c8 coverage (writes coverage/lcov.info)
tasks.register<Exec>("frontendTest") {
    group = "verification"
    description = "Runs the platform-frontend Cucumber BDD tests with coverage."
    workingDir("platform-frontend")
    commandLine("npm", "run", "test:coverage")
}

// Builds the frontend for production
tasks.register<Exec>("frontendBuild") {
    group = "build"
    description = "Builds the platform-frontend Vite application."
    workingDir("platform-frontend")
    commandLine("npm", "run", "build")
}

// Custom task: simulate priority scoring impact before deploying priorityConfig changes
tasks.register("simulatePriority") {
    group = "verification"
    description = "Simulates priority score impact of workflow-config.priorityConfig changes against live data."
    doLast {
        println("simulatePriority: not yet implemented — add implementation to platform-workflow")
    }
}

tasks.withType<JavaCompile>().configureEach {
    options.compilerArgs.add("-parameters")
}
