export const MOCK_SUBMISSION = {
  id: 'sub-e2e-1',
  tenantId: 'tenant-1',
  workflowType: 'E2E_TEST_TYPE',
  displayName: 'E2E Test Type',
  description: null,
  statusCode: 'DRAFT',
  statusDisplayName: 'Draft',
  submittedBy: 'analyst-1',
  submittedAt: null,
  reviewedBy: null,
  reviewedAt: null,
  rejectionReason: null,
  draftConfigs: {},
  currentStep: 1,
  version: 1,
  createdAt: '2024-01-01T00:00:00Z',
  updatedAt: '2024-01-01T00:00:00Z',
};
